name: Go

on: 
  push:
    branches:
    - "main"
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Build
      run: go build -o lnk_standalone
      env:
        GOOS: linux
        GOARCH: amd64
      
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "lnk_standalone"
        body: Build for linux amd64 for version ${{ env.RELEASE_VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
